---
title: ICE2

---
```{r}
install.packages(Tidyverse)
library(tidyverse)

```


```{r}
v <- c(1,4,4,3,2,2,3)
print(v)
```

```{r}
print(v[3])
#Index one element with number
```

```{r}
print(v[c(2,3,4)])

```

```{r}
print(v[c(2:4)])
```

```{r}
print(v[c(2,4,3)])
```

```{r}
df <- read.table(header=T, text='
subject sex size
     1  M  7
     2  F  6
     3  F  9
     4  M  11
')
print(df)
```

```{r}
print(df[1,3])
```

```{r}
print(df[1:2,])
```

```{r}
print(df[1:2, 2])
```

```{r}
df[1:2,c("sex","size")]
```

```{r}
df$sex
```

Index with a boolean vector
```{r}
f <- df$size >= 9
f

```

```{r}
df[f, ]
```

```{r}
df[df$size >=9, ]
```

Negative indexing

```{r}
print(v)
```

```{r}
print(v[-1])
```

```{r}
print(v[-1:-3])
```

```{r}
print(v)
print(length(v))
print(v[length(v)])
print(tail(v,1))
```

```{r}
library(tidyverse)
library(dplyr)
```
```{r}
ICEdata <- read_csv("ICE1_DATA.csv")
```

```{r}
ICEdata
```

```{r}
new_ICE <-select(ICEdata, 'DBN', 'Quality_Review_Score', 'Progress_Rpt_10-11')
new_ICE
```


Data manipulation in tidyverse
```{r}

collegeGraduation <- mutate(ICEdata, collegeGraduationRate ='college enroll 2010-11' / 'graduation 2010-11')
collegeGraduation
```
```{r}
filter(ICEdata, 'graduation 2010-11'> 0.8)
```

```{r}
filter(ICEdata, 'graduation 2010-11' > 0.8 & 'Quality_Review_Score' == "Proficient")
```

```{r}
new_ICE <- select (ICEdata, 'Quality_Review_Score', 'Student_Progress_10-11', 'graduation 2010-11')
filter(new_ICE, 'graduation 2010-11' > 0.8)
```
```{r}
ICEdata %>%
  select('Quality_Review_Score', 'Student_Progress_10-11', 'graduation 2010-11') %>%
  filter('graduation 2010-11' > 0.8)
```

```{r}
16 %>% sqrt()
```

```{r}
16 %>% sqrt() %>% log2()
```

```{r}
16 %>% sqrt() %>% log(base = 2)
```

```{r}
ICEdata %>% select('Quality_Review_Score', 'Student_Progress_10-11', 'graduation 2010-11') %>% filter('graduation 2010-11' > 0.8)
```

Combine Datasets
```{r}
v <- c(1,4,4,3,2,2,3)
v
```

```{r}
c(v,9)
```

```{r}
append(v,9)
```

```{r}
install.packages("nycflights13")
library(nycflights13)
```

```{r}

data(flights)
data(weather)

```

```{r}
view(flights)
view(weather)
```

```{r}
flights <- flights %>% select(carrier, flight, origin, dest, time_hour)
weather <-weather %>% select(temp, wind_speed, precip, origin, time_hour)
mergeCols <- c("origin", "time_hour")
```

```{r}
left_dplyr <- left_join(flights, weather, by=mergeCols)
right_dplyr <- right_join(flights, weather, by=mergeCols)
inner_dplyr <- inner_join(flights, weather, by=mergeCols)
full_dplyr <- full_join(flights, weather, by=mergeCols)

```

```{r}
g <-ICEdata %>%
  filter('Quality_Review_Score' == "Proficient") %>%
  summarise(average = mean('graduation 2010-11', na.rm=TRUE), standardDeviation=sd('graduation 2010-11', na.rm=TRUE))
g
```

```{r}
g$average
```

```{r}
ICEdata %>% group_by(Quality_Review_Score)

```

```{r}
ICEdata %>%
  group_by(Quality_Review_Score) %>%
  summarize(GraduationAverage = mean('graduation 2010-11', na.rm = TRUE), CollegeEnrollAverage = mean('college enroll 2010-11' , na.rm=TRUE))
```

```{r}
ICEdata %>% 
  group_by('Quality_Review_Score' , 'Progress_Rpt_10-11') %>%
  summarize(count =n())
```

