---
title: "ICE 5"
Name: Cleo You
---

```{r}
twoDData <-rbind(matrix(rnorm(100, mean=0, sd=0.3),ncol=2),
                 matrix(rnorm(100, mean=2, sd=0.2),ncol=2),
                        matrix(rnorm(100, mean=4, sd=0.5),ncol=2),
                               matrix(rnorm(100, mean=6, sd=0.2),ncol=2))
colnames(twoDData) <-c("x", "y")
plot(twoDData)
```
```{r}
c1 <- kmeans(twoDData, centers = 4)
```

```{r}
plot(twoDData, col=c1$cluster)
```

Silhourtte Coefficient and Silhoutte Plot
```{r}
#install.packages("cluster")
library(cluster)
```

```{r}
dis=dist(twoDData)^2
sil=silhouette(c1$cluster, dis)
plot(sil, col = c1$cluster)
```


```{r}
#install.packages("factoextra")
library(factoextra)
```

```{r}
fviz_silhouette(sil)
```

Clustering with k-means: Self-Reported Motivation
```{r}
library(tidyverse)
```

```{r}
motivation <-read_csv("ICE5_Data.csv")
```

```{r}
motivationClean <- motivation %>% na.omit() %>%
  select(-id)
motivationClean
```
```{r}
motivation2CL <- kmeans(motivationClean, centers = 2)
dis2CL = dist(motivationClean)^2
sil2CL = silhouette(motivation2CL$cluster, dis2CL)
fviz_silhouette(sil2CL)
```

```{r}
motivation3CL <- kmeans(motivationClean, centers = 3)
dis3CL = dist(motivationClean)^2
sil3CL = silhouette(motivation3CL$cluster, dis3CL)
fviz_silhouette(sil3CL)
```

```{r}
motivation4CL <-kmeans(motivationClean, centers = 4)
dis4CL=dist(motivationClean)^2
sil4CL = silhouette(motivation4CL$cluster, dis4CL)
fviz_silhouette(sil4CL)
```

```{r}
motivationClean %>% mutate(cluster=motivation3CL$cluster)
```

```{r}
fviz_nbclust(motivationClean, kmeans, method="wss")
```



