---
"title: ICE 8"
"Name: Cleo You"
---
```{r}
library(igraph)
library(tidyverse)
```
```{r}
SNAdata <-read.csv("ICE8_Data.csv", row.names=1)
g<- graph_from_adjacency_matrix(as.matrix(SNAdata), weighted=TRUE, mode="undirected")
plot(g)
```
```{r}
#Density
d <- edge_density(g)
d
```

```{r}
#Degree centrality
degree(g)
```

```{r}
betweenness(g, normalized=TRUE)
```

```{r}
betweenness(g, directed=FALSE, normalized=TRUE)
```

```{r}
#Community detection
fc <-cluster_fast_greedy(g)
# to see who is in which community
membership(fc)
```

```{r}
##to see how many communities we have identified
sizes(fc)
```
```{r}
#Visualizing
#to manipulate the vertex properties of the graph object 'g'
V(g)$color <-fc$membership
plot(g)
```

```{r}
#Multiplying the degree by 2 times
V(g)$degree <- degree(g)
plot(g, vertex.size=V(g)$degree*2)
```
```{r}
plot(g, vertex.size=V(g)$degree*2, edge.width=5^(E(g)$weight)/5)
```
```{r}
#For consistent Layout, you may to set seed
set.seed(123)
plot(g, 
     vertex.size=V(g)$degree*2,
     edge.width=5^(E(g)$weight)/5,
     layout=layout.fruchterman.reingold)
```





